//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSPC.UI.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSPC.UI.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _109_AllAnnotations_Default_16x16_72 {
            get {
                object obj = ResourceManager.GetObject("_109_AllAnnotations_Default_16x16_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _109_AllAnnotations_Error_16x16_72 {
            get {
                object obj = ResourceManager.GetObject("_109_AllAnnotations_Error_16x16_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap _109_AllAnnotations_Warning_16x16_72 {
            get {
                object obj = ResourceManager.GetObject("_109_AllAnnotations_Warning_16x16_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Buttons_Cancel {
            get {
                return ResourceManager.GetString("Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Buttons_Delete {
            get {
                return ResourceManager.GetString("Buttons_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Buttons_New {
            get {
                return ResourceManager.GetString("Buttons_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Buttons_Ok {
            get {
                return ResourceManager.GetString("Buttons_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to flight simulator OK.
        /// </summary>
        public static string MainWindow_ConnectedFSim {
            get {
                return ResourceManager.GetString("MainWindow_ConnectedFSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Vatsim OK.
        /// </summary>
        public static string MainWindow_ConnectedVatsim {
            get {
                return ResourceManager.GetString("MainWindow_ConnectedVatsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to flight simulator....
        /// </summary>
        public static string MainWindow_ConnectingToFSim {
            get {
                return ResourceManager.GetString("MainWindow_ConnectingToFSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Vatsim....
        /// </summary>
        public static string MainWindow_ConnectingToVatsim {
            get {
                return ResourceManager.GetString("MainWindow_ConnectingToVatsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to flight simulator.
        /// </summary>
        public static string MainWindow_NoConnectionFSim {
            get {
                return ResourceManager.GetString("MainWindow_NoConnectionFSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to Vatsim.
        /// </summary>
        public static string MainWindow_NoConnectionVatsim {
            get {
                return ResourceManager.GetString("MainWindow_NoConnectionVatsim", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap options {
            get {
                object obj = ResourceManager.GetObject("options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline callsign, e.g. NAX, SAS or DLH.
        /// </summary>
        public static string Options_AI_Airline {
            get {
                return ResourceManager.GetString("Options_AI_Airline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Models.
        /// </summary>
        public static string Options_AI_Header {
            get {
                return ResourceManager.GetString("Options_AI_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritized list of rules for AI model matching:.
        /// </summary>
        public static string Options_AI_Listheader {
            get {
                return ResourceManager.GetString("Options_AI_Listheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (ex. &apos;Beech King Air 350 Paint1&apos;).
        /// </summary>
        public static string Options_AI_Model {
            get {
                return ResourceManager.GetString("Options_AI_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft type designator, e.g. A320, B738 or MD82.
        /// </summary>
        public static string Options_AI_Planetype {
            get {
                return ResourceManager.GetString("Options_AI_Planetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule description:.
        /// </summary>
        public static string Options_AI_RuleDescription {
            get {
                return ResourceManager.GetString("Options_AI_RuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CID:.
        /// </summary>
        public static string Options_Conn_CID {
            get {
                return ResourceManager.GetString("Options_Conn_CID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Options_Conn_Header {
            get {
                return ResourceManager.GetString("Options_Conn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Options_Conn_Password {
            get {
                return ResourceManager.GetString("Options_Conn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real name:.
        /// </summary>
        public static string Options_Conn_Realname {
            get {
                return ResourceManager.GetString("Options_Conn_Realname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string Options_Conn_Server {
            get {
                return ResourceManager.GetString("Options_Conn_Server", resourceCulture);
            }
        }
    }
}
