//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSPC.UI.WPF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSPC.UI.WPF.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Buttons_Cancel {
            get {
                return ResourceManager.GetString("Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Buttons_Ok {
            get {
                return ResourceManager.GetString("Buttons_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATC ONLINE.
        /// </summary>
        public static string Main_ATCOnlineHeader {
            get {
                return ResourceManager.GetString("Main_ATCOnlineHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALLSIGN:.
        /// </summary>
        public static string Main_Callsign {
            get {
                return ResourceManager.GetString("Main_Callsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C/IDNT.
        /// </summary>
        public static string Main_CIdnt {
            get {
                return ResourceManager.GetString("Main_CIdnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECT.
        /// </summary>
        public static string Main_Connect {
            get {
                return ResourceManager.GetString("Main_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTED.
        /// </summary>
        public static string Main_Connected {
            get {
                return ResourceManager.GetString("Main_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTING.
        /// </summary>
        public static string Main_Connecting {
            get {
                return ResourceManager.GetString("Main_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLIGHTPLAN.
        /// </summary>
        public static string Main_Flightplan {
            get {
                return ResourceManager.GetString("Main_Flightplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQUAWK.
        /// </summary>
        public static string Main_Squawk {
            get {
                return ResourceManager.GetString("Main_Squawk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDBY.
        /// </summary>
        public static string Main_Stdby {
            get {
                return ResourceManager.GetString("Main_Stdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Main_TabTitleAll {
            get {
                return ResourceManager.GetString("Main_TabTitleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CID:.
        /// </summary>
        public static string Options_CID {
            get {
                return ResourceManager.GetString("Options_CID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Options_Password {
            get {
                return ResourceManager.GetString("Options_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real name:.
        /// </summary>
        public static string Options_Realname {
            get {
                return ResourceManager.GetString("Options_Realname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string Options_Server {
            get {
                return ResourceManager.GetString("Options_Server", resourceCulture);
            }
        }
    }
}
